services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
      - minio
    command: >
              sh -c "npx prisma migrate deploy &&
                    node dist/index.js"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/marketplace
      JWT_SECRET: supersecret
      S3_ENDPOINT: http://minio:9000
      S3_REGION: us-east-1
      S3_BUCKET: marketplace
      S3_ACCESS_KEY: admin
      S3_SECRET_KEY: admin123
    ports:
      - "4002:4001"
    volumes:
      - C:\Users\Admin\Documents\marketplace_data:/app/data      

  services:
  backend-dev:
    image: node:20-alpine
    working_dir: /app
    command: sh -lc "npm ci && npm run dev"
    ports:
      - "4002:4000"          # host 4002 -> contenedor 4000
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/marketplace
      - JWT_SECRET=devsecret
    volumes:
      - ./backend:/app       # monta tu código fuente
      - /app/node_modules    # evita pisar node_modules del contenedor
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      default:
        aliases:
          - minio      # para que el backend lo vea como http://minio:9000

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 admin admin123 &&
      mc mb -p local/marketplace || true &&
      mc admin config set local api cors_allow_origin='http://localhost:5173,http://127.0.0.1:5173,https://tudominio.com' &&
      exit 0
      "

volumes:
  postgres_data:
  minio_data:
