services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - minio
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/marketplace
      JWT_SECRET: supersecret
      S3_ENDPOINT: http://minio:9000
      S3_REGION: us-east-1
      S3_BUCKET: marketplace
      S3_ACCESS_KEY: admin
      S3_SECRET_KEY: admin123
    ports:
      - "4000:4000"

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - minio
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/marketplace
      JWT_SECRET: supersecret
      S3_ENDPOINT: http://minio:9000
      S3_REGION: us-east-1
      S3_BUCKET: marketplace
      S3_ACCESS_KEY: admin
      S3_SECRET_KEY: admin123
    ports:
      - "4001:4000"
    command: sh -c "npx prisma generate && npm run dev"

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      default:
        aliases:
          - minio      # para que el backend lo vea como http://minio:9000

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 admin admin123 &&
      mc mb -p local/marketplace || true &&
      mc admin config set local api cors_allow_origin='http://localhost:5173,http://127.0.0.1:5173,https://tudominio.com' &&
      exit 0
      "

volumes:
  postgres_data:
  minio_data:
